### ISSUE TITLE
Brain dump / bikeshed of what a  completed migration looks like

### ISSUE THREAD

**Issue by smikes** [npm/support-cli#5]
This is a bit disorganized.  My apologies.

The "migration" aspect of this project is complete when --
- [ ] New support issues are directed to this repository
- [ ] new support issues are likely to contain useful information
  - [ ] npm and node version
  - [ ] npm-debug.log (or link to gist of same)
  - [ ] proxy setup of npm
  - [ ] proxy setup of browser (via $http_proxy on *nix and ?? from registry on Windows)

Steps that can happen fast/early:
- [ ] factor out references to github.com/npm/npm/issues in npm & related modules 
- [ ] npm blog post pre-announcing the plan
- [ ] actually push it out and announce it

Future work / nice to have
- [ ] save/cache npm-debug.log ( https://github.com/npm/npm/issues/5214#issuecomment-49565969 )
- [ ] ensure npm-debug.log is written out on failure (https://github.com/npm/npm/issues/6350 )
- [ ] implement `npm ping` on client/cli side (already in server) ( https://github.com/npm/npm/issues/5750 )
- [ ] add latest `npm` and `node` versions to return of `npm ping`
- [ ] implement `npm doctor`
  - [ ] check for available node/npm upgrades
  - [ ] check for npm registry reachability
  - [ ] check for private registry reachability
  - [ ] cache clean
  - [ ](with --force?) rimraf `node_modules` and run a new `npm install` ?
- [ ] implement `npm report`
  - [ ] do non-destructive parts of `npm doctor`
  - [ ] upload relevant npm-debug logs to gist
  - [ ] take user to github issue page (or: an npm-hosted front-end for it?)
  - [ ] dynamic completion of possibly relevant wiki or troubleshooting topics as user types issue title
- [ ] write code that uploads `npm-debug.log` to anon gist and preserves the url (libraries exist that do this, so just interface with them)

Lots more ideas.  Just trying to separate 'immediate' from 'future'.  Comments/criticism/addition/bikeshedding very very welcome, please add more.

**Comment by faiq** [comment]
it would also be very dope if we had something like <a href="https://github.com/npm/npm/wiki/Troubleshooting">this</a> but maybe right on the front page, OR possibly on CONTRIBUTING.md
